name: HelloBasicGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo Hello~ 
      - name: List
        run: ls -al
      - name: version
        run: python -v
      - name: test run
        run: python 001_Test.py
              
