name: HelloBasicGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Files
        run: ls -al
      - name: package list
        run: pip list
      - name: Up-Grade pip
        run: python -m pip install --upgrade pip
      - name: Run Test.py
        run: python 001_BasicCrawler.py
              
